### ISSUE TITLE
Add support for Jupyter Notebook Debugger in VSCode

### ISSUE THREAD

**Issue by hongha912** [awulkiew/graphical-debugging-vscode#10]
This is an amazing extension and it works out of the box for many of my team's use cases--greatly enhanced our productivity! I have a quick question: is it possible to add support to [VS Code Jupyter Notebook Debugger](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_debug-a-jupyter-notebook)? Currently when trying to do so, the Graphical Watch panel would show the type of geometry, followed by "unknown" (even though the geometry is clearly valid), and the Graphical Watch display shows nothing.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/67204151/212961081-1599961a-13a8-4e6a-b8e6-ae82e8dd8666.png">

Seems like Jupyter Notebook VS Code debugger requires some additional installation https://github.com/microsoft/vscode-jupyter/wiki/Setting-Up-Run-by-Line-and-Debugging-for-Notebooks

If you can point me to possibly where the issue might be, I can attempt to open a PR myself?

**Comment by hongha912** [comment]
It's a Shapely Polygon which should have support out of the box -- and it works if I'm debugging tests / normal runs.

**Comment by awulkiew** [comment]
Fix: https://github.com/awulkiew/graphical-debugging-vscode/commit/afdeeb333801b5b242bdf76fe80dda8f498f867c
Will be released with v0.5.2
