### ISSUE TITLE
Visualize non boost geometry types

### ISSUE THREAD

**Issue by vvrs** [awulkiew/graphical-debugging-vscode#11]
From the documentation, it looks like this tool works for boost geometry types. I wondering if we can get this to visualize custom geometry types. At the moment, I am working with AlignedBox from Eigen [Geometry](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html) library. Any suggestions about visualizing this would be greatly appreciated.

**Comment by awulkiew** [comment]
Yes, you can: https://github.com/awulkiew/graphical-debugging-vscode#user-defined-types

**Comment by awulkiew** [comment]
I haven't used eigen but AFAIU you'd have to  define `AlignedBox` as a *box* with `m_min` and `m_max` points
https://github.com/libigl/eigen/blob/master/Eigen/src/Geometry/AlignedBox.h#L307
similar to Boost.Geometry `box`:
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/resources/boost.json#L196-L203

after defining `VectorType` used for `m_min` and `m_max` as *point*:
https://github.com/libigl/eigen/blob/master/Eigen/src/Geometry/AlignedBox.h#L40
similar to Boost.Geometry `point`:
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/resources/boost.json#L35-L42

Alternatively you could define `AlignedBox` using 4 coordinates extracted from matrices/vectors like it is done for Boost.Polygon `rectangle_data`:
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/resources/boost.json#L35-L42

If you had problems let me know.
