### ISSUE TITLE
FEAT: What would it take to get Java support?

### ISSUE THREAD

**Issue by latenitecoding** [awulkiew/graphical-debugging-vscode#12]
Would I be able to put together a JSON file to provide Java support?

**Comment by awulkiew** [comment]
Yes, you should be able to do this. You can put it in your workspace or clone this repo and put it in
https://github.com/awulkiew/graphical-debugging-vscode/tree/master/resources
if you're planning to run the develop version of the extension and create a PR later.

Only one java debugger is enabled right now with type `java`:
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/src/debugger.ts#L26
AFAIU it's this one (I may be wrong):
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug
If you're using a different one then it has to be added in `debugger.ts`.

**Comment by awulkiew** [comment]
@latenitecoding Have you tried it?

**Comment by awulkiew** [comment]
I tried it. After adding json to my workspace I was able to visualize array.
```
{
    "name": "graphicaldebugging",
    "language": "java",
    "types": [
        {
            "type": "[a-zA-Z_][\\w<,>:\\s]*\\[\\]",
            "kind": "container",
            "array": {
                "start": "$this",
                "size": "$this.length"
            },
            "_comment": "Java array"
        }
    ]
}
```

![obraz](https://github.com/user-attachments/assets/adcf7743-ebd2-4012-8dac-2b36fa1a4093)
![obraz](https://github.com/user-attachments/assets/6bceb0a2-88bf-4dc9-9a4d-a6b7be46a73c)
![obraz](https://github.com/user-attachments/assets/9a661229-3475-4e7f-8ac6-54bb6ad09092)
