### ISSUE TITLE
Can't get User-Defined types to work 

### ISSUE THREAD

**Issue by maxmarsc** [awulkiew/graphical-debugging-vscode#13]
Hi,

First of all thanks a lot for the work you put into this extension. It's really helpful !

I've been trying to add support for `Eigen::TensorFixedSize` class (amongst other ones).
Here is a screenshot of a variable I'm trying to draw :
![Screenshot from 2023-10-09 13-15-36](https://github.com/awulkiew/graphical-debugging-vscode/assets/28865168/c2cab60f-21b3-4b8e-ae34-0fe08e81acbc)

To catch this type I added this entry in a graphicaldebugging.json file :
```json
{
  "name": "graphicaldebugging",
  "language": "cpp",
  "types": [
    {
      "type": "Eigen::TensorFixedSize<.+>",
      "kind": "container",
      "array": {
        "start": "$this.m_storage.m_data",
        "size": "$this.m_storage.Size"
      }
    }
  ]
}
```

I deduced the `start` and `size` field values from the debugger panel :
![Screenshot from 2023-10-09 13-18-01](https://github.com/awulkiew/graphical-debugging-vscode/assets/28865168/ccd1b6cd-fb8c-457c-95ae-4d428f428be1)

Yet the type remains `unknown`.

PS : is there a way to enable a debug console log for the extension ? This would be helpful to identify what I'm missing

**Comment by JoostVisser** [comment]
Hi Max,

There currently aren't many logs written in the application.
One way you could figure out what's going wrong is by cloning this repository, installing it (`npm install`) and then press F5 to run the extension locally in debug mode.

**Comment by awulkiew** [comment]
This seems to work for me in ver 0.9. Maybe it was fixed along with other things.

![obraz](https://github.com/user-attachments/assets/e5a7a078-3759-4df5-8952-a0741b648c94)
![obraz](https://github.com/user-attachments/assets/d0c8170f-e2f6-4257-972d-74bde8e70934)
![obraz](https://github.com/user-attachments/assets/1319214d-410e-4176-a474-1ec8676f390d)

**Comment by awulkiew** [comment]
Btw, you did put `*.json` file in the workspace directory and **Additional Types Directory** extension setting is set to default `.`, correct?

**Comment by maxmarsc** [comment]
@awulkiew I confirm it works now, thanks a lot !

Also yes I confirm the default value for `graphicalDebugging.additionalTypesDirectory` is `.`
