### ISSUE TITLE
Add support for C#

### ISSUE THREAD

**Issue by JoostVisser** [awulkiew/graphical-debugging-vscode#15]
I'm currently developing C# in VSCode on Windows (using the C# Dev Kit) and I would love to use this extension.

On Windows, the sessionType of the default debugger used for CSharp is `coreclr`.

**Comment by awulkiew** [comment]
I'll release it with ver 0.9.

![obraz](https://github.com/user-attachments/assets/a15f490b-fd8e-4631-a3de-b33545b71a8f)
![obraz](https://github.com/user-attachments/assets/af89c512-3a3c-4128-a739-7a75761f16b2)

**Comment by awulkiew** [comment]
Added in ver 0.9
