### ISSUE TITLE
Not working for Python? It says "unknown (list)" for a simple list.

### ISSUE THREAD

**Issue by yanedge** [awulkiew/graphical-debugging-vscode#16]
![image](https://github.com/user-attachments/assets/91739df6-c4a2-4ec7-aa42-a06c8abfe378)

VSCode on Mac

**Comment by JoostVisser** [comment]
See #14 , I suspect they changed the name of the debugger and that needs to be updated.

**Comment by awulkiew** [comment]
It works for me on windows.

![obraz](https://github.com/user-attachments/assets/30edf78a-40d8-47d6-b105-a3b788a91f6d)
![obraz](https://github.com/user-attachments/assets/56359b48-2b84-4b3b-afe5-84468cd0ef9c)

Which extension do you use for python debugging?

**Comment by awulkiew** [comment]
Support added in ver 0.9
