### ISSUE TITLE
Visualization of description direction

### ISSUE THREAD

**Issue by TrackerSB** [awulkiew/graphical-debugging-vscode#4]
In context of contour operations especially union and intersect it is often valuable to know in which direction contours are described.

**Comment by awulkiew** [comment]
Good idea.

This is one possible way (all segments above certain displayed length have directions): https://github.com/awulkiew/graphical-debugging ? I'm not sure if plotly supports this. It's probable that we'd have to modify plotly for this.

Easier way would be to draw direction once on the longest segment. This would make analysis harder when zoomed however. 

What do you think?

**Comment by TrackerSB** [comment]
I don't it is required to mark all segments having at least a certain length. I think some indication (e.g. at the position of the last point) should suffice.

**Comment by awulkiew** [comment]
I've added triangle at the position of the first point: https://github.com/awulkiew/graphical-debugging-vscode/commit/2aaddbca18647aa8521fbd12e4e2b9405da677c9
Will be released with v0.6

![image](https://user-images.githubusercontent.com/1226951/218282337-23a0f884-6ef6-42e9-925b-310a3587c4a3.png)
