### ISSUE TITLE
Using graphical-Debugging together with Cortex-Debug

### ISSUE THREAD

**Issue by ssmahub** [awulkiew/graphical-debugging-vscode#5]
The graphical-debugger addon is just want I am looking for, .. 
but when I use it with Cortex-Debug (ARM Cortec-M GDB Debugger), 
I cannot  get it to load and show variables, when I make a breakpoint.
Not even a simple Int array ?

Using with an other debugger it works OK.

Any hints or fix ?

ssma

**Comment by awulkiew** [comment]
The problem probably is that currently the language is detected using the name of the debugger:
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/src/debugger.ts#L13-L27
and the name of the debugger you're using is not checked.

One solution would be to allow users to define debugger names in json file.

Another solution would be to detect language based on the extension of debugged file (I don't remember but I think this should be available somewhere).

What do you think?

**Comment by ssmahub** [comment]
Thanks for a quick answer :-)
I am working on it : 
adding 'cortex-debug' here:
 if (['cppvsdbg', 'cppdbg', 'lldb', 'cortex-debug'].includes(sessionType))
            return Language.Cpp;
.. did not do it.

Now looking more into my debugger cmds and what I think the Grahical-debugger expect - to show the simple data hej array:
 _int hej[10];_

In GRAPHICAL WATCH : writing "print hej" instead of just 'hej', return the array in as a text string in the DEBUG CONSOLE
every time the break point was hit ..

working on it 
best regards
ssma

**Comment by awulkiew** [comment]
I'll leave this open becasue this issue needs addressing. If you find something could you please share your findings here?

If my suggestion didn't work then unfortunately some debugging is necessary. FYI this is the function that is called when variable is processed (assuming that debugging session works properly and language was detected):
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/src/extension.ts#L11-L24

**Comment by awulkiew** [comment]
I've added `cortex-debug` to the list: https://github.com/awulkiew/graphical-debugging-vscode/commit/7f02a6dcdc1a64725949b61444da42337a182283
It will be released with v0.6.
It works for me:
![image](https://user-images.githubusercontent.com/1226951/218317415-10062427-f9fa-4b17-8904-a564cb8280c5.png)
