### ISSUE TITLE
Python numpy array support

### ISSUE THREAD

**Issue by Capsar** [awulkiew/graphical-debugging-vscode#6]
Hello,

This extension is one of a kind. 
Looking through the supported types in Python I saw that it was missing Numpy arrays.
It would be very nice to see support for this in the future, if guided to the correct spot I might be able to help with this.

Kind regards,
Caspar

**Comment by awulkiew** [comment]
I'm glad you like it.
Python types are defined here:
https://github.com/awulkiew/graphical-debugging-vscode/blob/master/resources/python.json
In case you didn't know, you can create your own json file with definitions of types you want to visualize and put it in your workspace or anywhere else after defining some directory in Settings.

**Comment by awulkiew** [comment]
Added in: https://github.com/awulkiew/graphical-debugging-vscode/commit/521d26afa923535e9fbcd9ea4d70aae948c77df8
Will be released with v0.5.2
