### ISSUE TITLE
What do $T and $N mean?

### ISSUE THREAD

**Issue by manch1n** [awulkiew/graphical-debugging-vscode#7]
I want to write a self configuration json file.
Here is the c++ code:
struct Point{
int x;
int y;
};
using ring = std::vector<Point>;

How can I write the correct json?

**Comment by awulkiew** [comment]
$T is template parameter, e.g. `std::array<int, 5>` `$T0` is `int`
$N is array size, e.g. for `int arr[5]` `$N0` is `5`

Define Point like this: https://github.com/awulkiew/graphical-debugging-vscode/blob/master/resources/boost.json#L83-L91

As for the vector AFAIR by default it will be visualized as container of points. You may try to define `std::vector<Point>` as a ring like this: https://github.com/awulkiew/graphical-debugging-vscode/blob/master/resources/boost.json#L204-L211 with container's name `$this`. By default rings are clockwise, you may set `cw` to `true`/`1`/`false`/`0` or `ccw` to `true`/`1`/`false`/`0`.

**Comment by manch1n** [comment]
Thanks for the reply!
I find that the default json doesn't support const and reference type.And I write the flowing json:
`        {
            "type": ".*ClipperLib::Polygon.*", // ".*" for const and &
            "kind": "polygon",
            "exteriorring": {
                "name": "$this.tr_cache_.Contour",
                "type": "ClipperLib::Path"
            }
        },
        {
            "type": ".*reference_wrapper.*ClipperLib::Polygon.*",
            "kind": "polygon",
            "exteriorring": {
                "name": "$this.get().tr_cache_.Contour", 
                "type": "ClipperLib::Path"
            }
        },
`
And I have to wait for half of minute to render one thunderd points polygon.Will there be something update for the performance and alias cv type?
Or Could I find an easy way to make an contribution for the project to support this?

**Comment by manch1n** [comment]
Thanks for the reply!
I find that the default json doesn't support const and reference type.And I write the flowing json:
`        {
            "type": ".*ClipperLib::Polygon.*", // ".*" for const and &
            "kind": "polygon",
            "exteriorring": {
                "name": "$this.tr_cache_.Contour",
                "type": "ClipperLib::Path"
            }
        },
        {
            "type": ".*reference_wrapper.*ClipperLib::Polygon.*",
            "kind": "polygon",
            "exteriorring": {
                "name": "$this.get().tr_cache_.Contour", 
                "type": "ClipperLib::Path"
            }
        },
`
And I have to wait for half of minute to render one thunderd points polygon.Will there be something update for the performance and alias cv type?
Or Could I find an easy way to make an contribution for the project to support this?

**Comment by awulkiew** [comment]
Regarding the performance: https://github.com/awulkiew/graphical-debugging-vscode/issues/2
Direct memory access is a lot of work.
Adding support for references, pointers and cv types should probably be easy. If you want to play with it one possible solution would be to parse variable's type only for C++ somewhere at the beginning of this method: https://github.com/awulkiew/graphical-debugging-vscode/blob/9fdd00e7ef9b686557404921e9ffe7bc5a9f5611/src/loader.ts#L1008 and to alter type and name based on the original type.

**Comment by awulkiew** [comment]
@manch1n cv types and references are supported in version 0.8. Could you give it a try?

**Comment by manch1n** [comment]
It works well.Thanks a lot!
