### ISSUE TITLE
Keep aspect ratio

### ISSUE THREAD

**Issue by TrackerSB** [awulkiew/graphical-debugging-vscode#8]
In order to make it easier to understand the shape of geometry (especially ellipses and long rectangles) it would be very helpful to scale x and y axes the same.

**Comment by awulkiew** [comment]
I agree but it may not be possible in Plotly.

**Comment by awulkiew** [comment]
Added here: https://github.com/awulkiew/graphical-debugging-vscode/commit/8cf0dade5c4815a9eacb60cd84dd6242b09875b1
Will be released with v0.5.2
